name: example
description: "Example that demostrate how to use the Animated Book List package."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Animated Book Widget package, by the-d-velopers.
  # TODO: Add URL here
  animated_book_widget:
    path: ../ 
  
  # Adds the Cupertino Icons font to your application. Used by the
  # CupertinoIcons class for iOS style icons, by Google flutter.dev.
  # https://pub.dev/packages/cupertino_icons  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  
  assets:
    - assets/icons/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

